### ISSUE TITLE
Show "good" vs "bad" superposition

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#19]
Might be nice to have a simple example to demonstrate the following statement:

> The cath-superpose tool makes superpositions that look better (but have higher RMSDs).

e.g. "bad" superposition with "good" RMSD (and vice versa)

**Comment by tonyelewis** [comment]
Again...

Good point - thanks. I've added an example [here](http://cath-tools.readthedocs.io/en/latest/tools/cath-superpose). Let me know your thoughts if you have suggestions or close this issue if you think it's adequately resolved. Ta.

**Comment by tonyelewis** [comment]
Great - thanks for fixes and changes in c0be6f8b1eaeecb4c82a72a6211b269097b78d70 and 04d827bc1f809e23065e2f5f2a708b621b2410a9.

I think you've done a good job of making my text flow better but I think I'm just trying to say too much in the caption anyway. I shouldn't have done it like a figure in a paper; it should just be a pretty, quick sell before the docs; I think I should just be saying:
 * your superpositions might have this problem
 * `cath-superpose` does it better
 * caveat: RMSD

Also, I agree that it's nice to have the line before the figure (and I tried that too) but that breaks the flow the start of the next paragraph ("It does this by focusing [...]").

I've had a go at:
 * being more brutal on shortening the caption and
 * better separating the figure and caption from the text below so that we lose less by moving that line down

I'll submit the proposed changes as a PR so we can discuss the details there.

**Comment by tonyelewis** [comment]
Please take a look at #20 and comment/edit/merge as you see fit. Ta.
