### ISSUE TITLE
Add 2DSEC (multiple alignment plots)

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#29]
2DSEC takes a multiple structural alignment file and outputs a postscript image of the conserved secondary structures. 

We have had a request to make 2DSEC images available for others to use and IIRC the only dependency is that the input file is in CORA format (which cath-superpose should be able to do).

![2dsec](https://cloud.githubusercontent.com/assets/152954/22733811/471e806c-edeb-11e6-8608-ea7d5a533ba7.png)

**Comment by tonyelewis** [comment]
Closing this for now because @sillitoe and I discussed it and, though we like several long-term ideas, it's less clear what can usefully be done here in the shortish term.

In particular, the multiple-alignment that `cath-superpose` generates ATM is a rough one built by gluing pairwise SSAP alignments together. This is good enough to generate good superpositions but can be somewhat sparse in places and so isn't recommended for this sort of application.

Two things we discussed:
 * it'd be good to do be able to handle this sort of thing in-browser with something like [D3](https://d3js.org/)
 * in some contexts, it might be helpful to have a *secondary-structure* colourer so it can be applied to alignment HTML (`--aln-to-html-file`). See#33.

In the short term, @sillitoe plans to investigate whether the original user request can be satisfied in a simple way, perhaps by giving them 2DSEC (binary/source?), which they can use on pairwise SSAP alignments?
