### ISSUE TITLE
Unexpected superposition

### ISSUE THREAD

**Issue by nataliedawson** [UCLOrengoGroup/cath-tools#34]
When running:

`$ SSAP $1 $2`
`$ cath-superpose --ssap-aln-infile="$1$2.list" --pdb-infile="$DOMDIR/$1" --pdb-infile="$DOMDIR/$2" --sup-to-pymol-file="$1_$2.pml"`
`$ pymol $1_$2.pml`

where `$DOMDIR=/cath/data/current/pdb`, `$1=2lf0A01` and `$2=1lrzA03`

The structural comparison with SSAP reported: a good SSAP score (78.25), good SSAP overlap (88%), and a poor RMSD (8.73A).

The issue:

Upon loading the .pml file with pymol, the two domains are superposed at a strange angle and show very little overlap, despite the very good overlap value calculated.

(Please note that I've added a .pdb.txt suffix to the domain PDB files as it would not support the filetype of the original file)

[1lrzA03.pdb.txt](https://github.com/UCLOrengoGroup/cath-tools/files/1081168/1lrzA03.pdb.txt)
[2lf0A01.pdb.txt](https://github.com/UCLOrengoGroup/cath-tools/files/1081167/2lf0A01.pdb.txt)

**Comment by tonyelewis** [comment]
The short version: use `cath-ssap` instead of `SSAP` and everything's OK:

![sup](https://user-images.githubusercontent.com/9743330/27285851-f89cbf18-54f5-11e7-8b60-b24dcd61b0bb.jpg)

It turns out that the problem is basically that the alignment generated by `SSAP` is a bit dodgy and that's what causes the not-very-good superposition. `cath-ssap` does a better job.

**Comment by tonyelewis** [comment]
(...but this took me quite a while to figure out and triggered me to make some really useful improvements so it was a really worthwhile issue - thanks!)
