### ISSUE TITLE
Run directly from PDB files

### ISSUE THREAD

**Issue by sillitoe** [UCLOrengoGroup/cath-tools#5]
A placeholder for a known (non-trivial) issue.

Would be great if the algorithm can run directly from PDB (or mmCIF) files rather than requiring the user to generate their own `*.sec` and `*.wolf` files.

**Comment by tonyelewis** [comment]
Some rough notes on the current status...

SNAP
----

SNAP is designed to run quickly without needing secondary structure to do so. Hence it runs directly from PDBs. However it isn't yet finished.

SSAP
----

SSAP requires DSSP/WOLF/sec files for secondary structure so I guess making it run without them would require either:
 * changing the algorithm to no longer require secondary structure (a big deal because the use of secondary structure is major ingredient in SSAP's speed) or
 * changing the code to be able to get secondary structure itself, either by:
   * running DSSP (or equivalent) itself, possibly caching results files - so DSSP/WOLF must still be installed and the files are still required but the executable handles their generation/caching
   * performing its own secondary structure assignments

I think SSAP requires sec files for their more coherent stretches of secondary structure. Again, making it run without them would require making it run secmake to generate them (and then possibly cache them) itself or making it try to do its own sensible calculations.

**Comment by jdt42** [comment]
As a user I agree that it would be great to run directly from pdb files.  In the meantime sec files can be generated from the secmake binary at https://github.com/UCLOrengoGroup/secmake

**Comment by tonyelewis** [comment]
This was implemented in [release:v0.12.25](https://github.com/UCLOrengoGroup/cath-tools/releases/tag/v0.12.25).
