### ISSUE TITLE
Build failure on Arch Linux

### ISSUE THREAD

**Issue by anadon** [UCLOrengoGroup/cath-tools#57]
It looks like the CMakeLists.txt requires ${LSB_RELEASE_CODE} to be something like Ubuntu or RHEL.  But some of the more up to date distros like Arch, Gentoo, and Clear have some pretty clear advantages.  It also looks like it hasn't been updated for Ubuntu 17.04, 17.10, or the upcoming 18.04 which is a LTS release.

It looks like there is some reason for the change for Ubuntu 16.10 only using dynamic libraries, but the standard currently is to only use dynamic libraries for this sort of thing, or have a switch.  Before I commit a patch, what is going on here?

**Comment by tonyelewis** [comment]
Thanks for contributing to cath-tools.

###  `LSB_RELEASE_CODE`

That make sense. Thanks. Let's see how the #60 build goes.

### 16.10

I think that only applies for the [GSL](https://www.gnu.org/software/gsl/). In general, I want to static-link to GSL because I don't want users to have to install GSL to run the pre-compiled executables. But there was a problem with the static library in Ubuntu 16.10, so I used a quick work-around of dynamic linking for that release.

**Comment by tonyelewis** [comment]
I've merged #60.
