### ISSUE TITLE
Allow cath-tools to build using libgsl.so in addition to libgsl.a

### ISSUE THREAD

**Issue by anadon** [UCLOrengoGroup/cath-tools#61]
More Arch Linux related things, which typically cascade out to other distributions after a few years.

cath-tools requires a static library for GSL, but my systems only provide a .so.  Given that this is likely to be the standard behavior for more distributions in the future, I'll be throwing another small merge request shortly.

I think I didn't catch this because I tested that part only on Ubuntu 17.10, and only checking the configuration on arch.

**Comment by anadon** [comment]
I'm looking into how to infer which type of library is supported, but it looks like it might require a manual switch.  Can I get someone else's thoughts on this?

**Comment by tonyelewis** [comment]
I'm open to you issuing a PR to add some sort of manual switch to allow you to use shared in your case. But I want static to remain the default because I want the default build to create executables that work on a machine equivalent to the build machine but without GSL installed.

Perhaps you could use a suitably named environment variable (eg `CATH_TOOLS_STATIC_LINK_GSL`) and detect the presence of that in `CMakeLists.txt`?

**Comment by anadon** [comment]
OK.  I'll get to adding that tomorrow.  It will also need an addition in the documentation, which I don't think I can edit.

**Comment by tonyelewis** [comment]
Do you mean the documentation on Read the Docs? That's generated from the files in the `docs` subdirectory (eg https://github.com/UCLOrengoGroup/cath-tools/blob/736d31ce30ec97c5873e179b20226ddad788f829/docs/build.md)

**Comment by anadon** [comment]
I stand corrected.

**Comment by tonyelewis** [comment]
NP :smiley:
