### ISSUE TITLE
min-dc-hmm-coverage flag meaning

### ISSUE THREAD

**Issue by nsneeladrisen** [UCLOrengoGroup/cath-tools#75]
for the cath-resolve-hits command, this flag has no associated function in the help section. Adding it will be helpful!

**Comment by tonyelewis** [comment]
The reason it isn't documented in the usage message is because it _doesn't exist and you never saw it_ :wave:.

Well… OK… it does exist. But it isn't an official, publicly-supported option; it's a hacky thing we bunged in because it was convenient for our OrengoGroup needs at the time.

If you're in the know, you can run `./cath-resolve-hits --hidden-help` and then the usage message includes:

```
[…]
Hit filtering [hidden options]:
  --min-hmm-coverage [=<percent>(=50)]           [IN PUBLIC GENE3D COMMAND] In hmmsearch_out input, ignore any hits for which 100.0 * ( hmm_to + 1 - hmm_from ) / hmm_length  <  <percent>
  --min-dc-hmm-coverage [=<percent>(=80)]        [IN PUBLIC GENE3D COMMAND] In hmmsearch_out input, ignore any /^\dc_{32}$/ hits for which 100.0 * ( hmm_to + 1 - hmm_from ) / hmm_length  <  <percent>
[…]
```

I'm open to discussion about how to improve things.
